name: milano-fix-it-smart
static_sites:
  - name: web
    source_dir: dist
    github:
      repo: your-repo-name
      branch: main
    build_command: npm run build
    routes:
      - path: /
      - path: /[^.]*
        file: index.html